# Generated by Django 3.2.14 on 2022-08-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220807_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='judul-slug', max_length=100),
        ),
    ]
